# Generated by Django 3.1.5 on 2021-03-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='matricule',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
