# Generated by Django 3.1.5 on 2021-03-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samabus', '0002_auto_20210315_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='heure',
            field=models.CharField(max_length=20),
        ),
    ]
