# Generated by Django 3.1.5 on 2021-03-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samabus', '0003_auto_20210315_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='valide',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
