# Generated by Django 3.1.5 on 2021-03-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samabus', '0004_voyage_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='place_max',
            field=models.IntegerField(null=True),
        ),
    ]
