# Generated by Django 3.1.5 on 2021-03-16 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samabus', '0009_remove_voyage_id_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='id_bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='samabus.bus'),
        ),
    ]
