# Generated by Django 3.1.5 on 2021-03-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samabus', '0010_voyage_id_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='id_bus',
        ),
    ]
