# Generated by Django 3.1.5 on 2021-03-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samabus', '0011_remove_reserve_id_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='prix',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
